# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-05 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='publisher_id',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='topic_id',
            new_name='topic',
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=50, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='parent_message',
            field=models.IntegerField(default=0, verbose_name='关联的留言id'),
        ),
    ]
